version: 2.1

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:22.16

jobs:
  checks:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies (only on cache miss)
          command: |
            if [ -d node_modules ]; then
              echo "node_modules restored from cache; skipping install"
            else
              npm ci
            fi
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules
      - run:
          name: Lint
          command: npm run test:lint
      - run:
          name: Typecheck
          command: npm run typecheck
      # - run:
      #     name: Unit tests
      #     command: npm run test:unit

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies (only on cache miss)
          command: |
            if [ -d node_modules ]; then
              echo "node_modules restored from cache; skipping install"
            else
              npm ci
            fi
      - run:
          name: Trust SSH key
          command: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: npm run semantic-release

  build_image:
    <<: *defaults
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install jq
          command: apk add --no-cache jq
      - run:
          name: Build Docker image
          command: docker build -t app .
      - deploy:
          name: Push Docker image
          command: |
            docker login ghcr.io -u gridcat -p${CR_PAT}
            NAME=$(jq -r '.name' package.json)
            VERSION=$(jq -r '.version' package.json)
            docker tag app "ghcr.io/gridcat/${NAME}:${VERSION}"
            docker push "ghcr.io/gridcat/${NAME}:${VERSION}"
            docker tag app "ghcr.io/gridcat/${NAME}:latest"
            docker push "ghcr.io/gridcat/${NAME}:latest"

workflows:
  ci:
    jobs:
      - checks:
          filters:
            tags:
              ignore: /.*/

      - release:
          context: semantic-release
          requires:
            - checks
          filters:
            branches:
              only: master

  deploy-tag:
    jobs:
      - build_image:
          context: git-container-registry
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^grc-hub-frontend-v.*/
