version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:14

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  bundle:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: npm-v1-{{ checksum "packages/grc-stamp-fronend/package-lock.json" }}
      - run: cd ~/packages/grc-stamp-fronend && npm ci
      - save_cache:
          key: npm-v1-{{ checksum "packages/grc-stamp-fronend/package-lock.json" }}
          paths:
            - ~/app/packages/grc-stamp-fronend/node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  run_test:
    <<: *defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: run tests
          command: cd ~/packages/grc-stamp-fronend && npm run test


  run_lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run JS Linter
          command: cd ~/packages/grc-stamp-fronend && npm run lint

  run_typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run typechecks
          command: cd ~/packages/grc-stamp-fronend && npm run typecheck

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Trust this ssh key
          command: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: cd ~/packages/grc-stamp-fronend && npm run semantic-release

  build_image:
    <<: *defaults
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Get the recent changes
          command: git pull origin master
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --no-cache jq
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd ~/packages/grc-stamp-fronend && docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            cd ~/packages/grc-stamp-fronend && docker save -o /caches/app.tar app
      - deploy:
          name: Push application Docker image
          command: |
            docker login ghcr.io -u gridcat -p${CR_PAT}
            docker tag app "ghcr.io/gridcat/$(jq -r '.name' package.json):$(jq -r '.version' package.json)"
            docker push "ghcr.io/gridcat/$(jq -r '.name' package.json):$(jq -r '.version' package.json)"
            docker tag app "ghcr.io/gridcat/$(jq -r '.name' package.json):latest"
            docker push "ghcr.io/gridcat/$(jq -r '.name' package.json):latest"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code

      - bundle:
          requires:
            - checkout_code

      - run_lint:
          requires:
            - bundle

      - run_typecheck:
          requires:
            - bundle

      - run_test:
          requires:
            - bundle

      - release:
          filters:
            branches:
              only: master
          requires:
            - run_test
            - run_typecheck
            - run_lint
          context: semantic-release
      
      - build_image:
          filters:
            branches:
              only: master
          requires:
            - release
          context: git-container-registry
